-- +goose Up
-- +goose StatementBegin
-- 初始数据库结构

CREATE TABLE IF NOT EXISTS users (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	email TEXT UNIQUE NOT NULL,
	password_hash TEXT NOT NULL,
	quota INTEGER DEFAULT 0,
	active INTEGER DEFAULT 1,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS domains (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT UNIQUE NOT NULL,
	active INTEGER DEFAULT 1,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS aliases (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	from_addr TEXT UNIQUE NOT NULL,
	to_addr TEXT NOT NULL,
	domain TEXT NOT NULL,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS mails (
	id TEXT PRIMARY KEY,
	user_email TEXT NOT NULL,
	folder TEXT NOT NULL,
	from_addr TEXT NOT NULL,
	to_addrs TEXT NOT NULL,
	cc_addrs TEXT,
	bcc_addrs TEXT,
	subject TEXT,
	size INTEGER NOT NULL,
	flags TEXT,
	received_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS totp_secrets (
	user_email TEXT PRIMARY KEY,
	secret TEXT NOT NULL,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (user_email) REFERENCES users(email) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_mails_user_folder ON mails(user_email, folder);
CREATE INDEX IF NOT EXISTS idx_mails_received_at ON mails(received_at);
CREATE INDEX IF NOT EXISTS idx_aliases_from ON aliases(from_addr);
CREATE INDEX IF NOT EXISTS idx_aliases_domain ON aliases(domain);
-- +goose StatementEnd
